version: '3.8'

networks:
  etudiants-network-swarm:
    driver: overlay
    name: etudiants-network-swarm

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.swarmMode=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"     # HTTP
      - "8080:8080" # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - etudiants-network-swarm
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"

  postgres:
    image: localhost:5000/etudiants-postgres
    deploy:  
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      resources:
        limits:
          cpus: '1.0'
          memory: '1.5G'
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.postgres.loadbalancer.server.port=5432"
        - "traefik.http.routers.postgres.rule=Host(`postgres.local`)"
        - "traefik.http.routers.postgres.service=postgres"
    volumes:
      - etudiants-data:/var/lib/postgresql/data
    networks:
      - etudiants-network-swarm
    environment:
      POSTGRES_PASSWORD: iinnpptt
      POSTGRES_USER: postgres
      POSTGRES_DB: etudiants
      POSTGRES_HOST_AUTH_METHOD: "md5"

  backend:
    image: localhost:5000/etudiants-backend
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.75'
          memory: 1G
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.backend.loadbalancer.server.port=8080"
        - "traefik.http.routers.backend.rule=Host(`backend.local`)"
        - "traefik.http.routers.backend.service=backend"
    networks:
      - etudiants-network-swarm
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/etudiants

  frontend:
    image: localhost:5000/etudiants-frontend
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.frontend.loadbalancer.server.port=80"
        - "traefik.http.routers.frontend.rule=Host(`frontend.local`)"
        - "traefik.http.routers.frontend.service=frontend"
    networks:
      - etudiants-network-swarm
    environment:
      BACKEND_URL: http://backend:8080
    depends_on: 
      - backend

volumes:
  etudiants-data:
    external: true