version: '3.8'

networks:
  etudiants-network-swarm:
    driver: overlay
    name: etudiants-network-swarm

services:
  nginx:
    image: nginx:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    networks:
      - etudiants-network-swarm
    depends_on:
      - frontend
      - backend
      
  postgres:
    image: localhost:5000/etudiants-postgres
    deploy:  
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      resources:
        limits:
          cpus: '1.0'
          memory: '1.5G'
    volumes:
      - etudiants-data:/var/lib/postgresql/data
    networks:
      - etudiants-network-swarm
    environment:
      POSTGRES_PASSWORD: iinnpptt
      POSTGRES_USER: postgres
      POSTGRES_DB: etudiants
      POSTGRES_HOST_AUTH_METHOD: "md5"

  backend:
    image: localhost:5000/etudiants-backend
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.75'
          memory: 1G
    networks:
      - etudiants-network-swarm
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://etudiants-stack_postgres:5432/etudiants

  frontend:
    image: slihatim/etudiants-frontend:1.6
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    networks:
      - etudiants-network-swarm
    environment:
      BACKEND_URL: http://localhost/api
    depends_on: 
      - backend

volumes:
  etudiants-data:
    external: true